### ISSUE TITLE
Why bluebird dependency

### ISSUE THREAD

**Issue by ibc** [brillout/promise-serial#3]
Nowadays there is no reason to mandate the usage of bluebird for having promises.

**Comment by brillout** [comment]
True, feel free to do a PR.
Since I'm now using `await` and `async` I'm less and less using `promise-serial`.

**Comment by ibc** [comment]
Done in #4

**Comment by brillout** [comment]
Merged. (Feel free to do whatever you want with my collaboration invitation.)
